### ISSUE TITLE
isMood, some stats are wrong

### ISSUE THREAD

**Issue by Sandbird** [Covid-19-Response-Greece/covid19-data-greece#7]
Some of the stats that ismood has are wrong, particularly with the 'new deaths per day'.
Here are the correct data (based on the ΕΟΔΥ pdfs)
2020-04-11 - 3 new deaths
2020-05-21 - 1 new death
2020-05-28 - 2 new deaths
2020-07-07 - 1 new death
2020-07-20 - 1 new death
2020-07-21 - 2 new deaths
2020-07-22 - 3 new deaths

I will try and contact them about it...but don't get your hopes up...they still haven't replied to a simple question i asked.

**Comment by AlexDelitzas** [comment]
Hi @Sandbird. Thanks for the notice!

We recommend using Johns Hopkins CSSE as a source for data concerning deaths. Check right [here](https://github.com/Covid-19-Response-Greece/covid19-data-greece/blob/master/data/greece/JohnsHopkinsCSSE/timeseries_greece.json).
